package org.web.hsqldb.domain;

// default package
// Generated 31/01/2014 22:30:38 by Hibernate Tools 3.4.0.CR1

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	private Integer empid;
	private String empname;
	private int empage;
	private long salary;
	private String address;

	public Employee() {
	}

	public Employee(String empname, int empage, long salary, String address) {
		this.empname = empname;
		this.empage = empage;
		this.salary = salary;
		this.address = address;
	}

	public Integer getEmpid() {
		return this.empid;
	}

	public void setEmpid(Integer empid) {
		this.empid = empid;
	}

	public String getEmpname() {
		return this.empname;
	}

	public void setEmpname(String empname) {
		this.empname = empname;
	}

	public int getEmpage() {
		return this.empage;
	}

	public void setEmpage(int empage) {
		this.empage = empage;
	}

	public long getSalary() {
		return this.salary;
	}

	public void setSalary(long salary) {
		this.salary = salary;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
