package org.web.hsqldb.domain;

// default package
// Generated 31/01/2014 22:30:38 by Hibernate Tools 3.4.0.CR1

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {

	private Integer id;
	private String firstName;
	private String lastName;
	private Double money;

	public Person() {
	}

	public Person(String firstName, String lastName, Double money) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.money = money;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Double getMoney() {
		return this.money;
	}

	public void setMoney(Double money) {
		this.money = money;
	}

}
